### ISSUE TITLE
v0.3.26 has a subtle breaking change

### ISSUE THREAD

**Issue by assafmo** [japaric/xargo#342]
Hi guys, please see this commit message on our project's repo: https://github.com/scrtlabs/SecretNetwork/commit/a8f623f5b375575f89b7a0da3ee52ac4a5ec7ef0

> Pin xargo to v0.3.25
>
> As xargo v0.3.26 contains breaking changes, specifically this: https://github.com/japaric/xargo/compare/v0.3.25...v0.3.26diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L147-R148 which caused an `error[E0463]: can't find crate for "core"` error when building

This is because of the change to the search path of sysroot. You might want to also tag v0.3.26 as v0.4.0.

Cc @reuvenpo

**Comment by RalfJung** [comment]
Your link is broken, I assume you mean [this one](https://github.com/japaric/xargo/compare/v0.3.25...v0.3.26#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L147-R148). (EDIT: ah fun, github breaks this link)

That diff comes from https://github.com/japaric/xargo/pull/338. That's just a doc change though, it does not change behavior. This folder it mentions (`src` in the Rust repository) has been wrong for years (ever since the Rust standard library was moved to `library`), and I finally fixed the docs.

Whatever problem you are seeing is definitely not caused by #338.
