### ISSUE TITLE
Update rustc version from 1.88.0 to 1.89.0 ，get a compiling error at xargo v0.3.26

### ISSUE THREAD

**Issue by Lee-watashi** [japaric/xargo#350]
docs changed in 1.89.0
[method.try_lock_shared](https://doc.rust-lang.org/stable/std/fs/struct.File.html#method.try_lock_shared)

```
error[E0308]: mismatched typesc
   --> /home/XXXXX/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/xargo-0.3.26/src/flock.rs:118:41
    |
118 |                 acquire(msg, &path, &|| f.try_lock_shared(), &|| f.lock_shared())?;
    |                                         ^^^^^^^^^^^^^^^^^^^ expected `Result<(), Error>`, found `Result<(), TryLockError>`
    |
    = note: expected enum `std::result::Result<_, std::io::Error>`
               found enum `std::result::Result<_, std::fs::TryLockError>`
help: use `?` to coerce and return an appropriate `Err`, and wrap the resulting value in `Ok` so the expression remains of type `Result`
    |
118 |                 acquire(msg, &path, &|| Ok(f.try_lock_shared()?), &|| f.lock_shared())?;
    |                                         +++                   ++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `xargo` (lib) due to 1 previous error
```

**Comment by maratik123** [comment]
Seems that this repo is abandoned for 5 years ago. No new releases since then.

**Comment by maratik123** [comment]
@Lee-watashi 

Why did you close this issue? Problem is not going anywhere.

This is still not working with rust-1.89.0:
```bash
cargo install --locked -f xargo
```

This issue will be automatically closed on merging #349

**Comment by Lee-watashi** [comment]
> [@Lee-watashi](https://github.com/Lee-watashi)
> 
> Why did you close this issue? Problem is not going anywhere.
> 
> This is still not working with rust-1.89.0:
> 
> cargo install --locked -f xargo
> This issue will be automatically closed on merging [#349](https://github.com/japaric/xargo/pull/349)

Sorry!

I'm a Git beginner, this was my first time submitting an issue on Git. When I learned that this repository might be abandoned, I closed the issue.

now the issue is reopen

**Comment by qwandor** [comment]
I'm seeing the same issue.

**Comment by Rylan-Meilutis** [comment]
same as well, Cross is broken as a result and trying to build images results in failure at the build stage

**Comment by fightling** [comment]
same

**Comment by JulieSapir** [comment]
same

**Comment by JulieSapir** [comment]
[xargo_fork](https://github.com/JulieSapir/xargo) I tried using Gemini to get it to build. It works fine on my device (rustc 1.95.0). Use it at your own risk.
